### PR TITLE
TKG_VMC_deploymentguide _2.1.0

### PR DESCRIPTION
**Pull request by bbharathan**
TKG_VMC_deploymentguide _2.1.0

### CODE REVIEW

**Review by reshmarajkumar-vmw — COMMENTED** [review]
Comments added inline

**Review by reshmarajkumar-vmw — APPROVED** [review]
Review completed and finalized over call.

**Comment by smuthukumar-vmw** [comment]
Checks are queued and not triggered.

**Comment by smuthukumar-vmw** [comment]
Reopening for checks completion

**Pull request merged**
