### PR TITLE
Make local testing easy

### PR DESCRIPTION
**Pull request by carlosonunez**
This pull request adds a Docker Compose service that makes it easy for
contributors to locally test their contributions before entering the
CI/CD process.

See the changes proposed in `CONTRIBUTING.md` and `TESTING.md` for more
information on how to use this service.

Signed-off-by: Carlos Nunez <ncarlos@vmware.com>

### CODE REVIEW

**Comment by carlosonunez** [comment]
@craigtracey PTAL!

**Comment by z4ce** [comment]
hey @carlosonunez it looks like your commits are still missing the sign-off message. You'll need to either amend both your commits or squash and sign off on the one squashed commit.

**Comment by craigtracey** [comment]
@carlosonunez are you proposing this as an alternative to simply running `act` locally as outlined in `TESTING.md`? Is there a particular advantage to running via `docker-compose` vs. `act`?

**Comment by carlosonunez** [comment]
Hey, Craig! Yes, I’m proposing it as an alternative for those that cannot or do not want to install binaries onto their system (hence using `docker-compose`).

**Comment by craigtracey** [comment]
Sorry it took a moment to come back around to this. I think I would like to recommend that the supported path is to use `act` directly, but that we also bring this change in as an alternative `docker-compose`-based test harness. 

Does that work? Can we rework the guidance in `TESTING` to reflect that?

**Comment by carlosonunez** [comment]
I'm okay with this being an alternative.

**Comment by carlosonunez** [comment]
@craigtracey PTAL

**Review by craigtracey — APPROVED** [review]

**Pull request merged**
