### PR TITLE
Closes Issue #10 and Updates Deployment Guide and Fixes Automation

### LINKED ISSUE #10: Azure RA needs outbound n/w for SaaS svcs
Enhance RA to include outbound network connectivity so that TKGm clusters can talk to TO/TMC/TSM, that run on AWS.

### PR DESCRIPTION
**Pull request by brharr**
Closes #10 

Updates to Deployment Guide to include SaaS Services and Fixes to Automation

### CODE REVIEW

**Comment by craigtracey** [comment]
@brharr I will be looking at this further today. 

Between this and https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/pull/38, we need to have a better means of organizing code vs. content, as I am not sure that we should (or even can) publish these types of linked assets.

**Comment by brharr** [comment]
@craigtracey Just want to make sure to provide some clarification based on the check failures.

In looking at the two checks that failed, I did not know that a signoff was required. I can certainly do that in the future. 

As for the spell check, it is bombing on a file name which is correct, but of course it is not a valid word. Not sure what I can do in that situation.

**Comment by z4ce** [comment]
@brharr I think something went wrong on a rebase.. it looks like you're reapplying prior commits

**Comment by brharr** [comment]
@z4ce 
> @brharr I think something went wrong on a rebase.. it looks like you're reapplying prior commits

I had nothing but problems trying to get my changes and all of Meera's changes applied because of the diffs and the way that they work. I believe that everything is correct though as far as the edits are concerned.

**Comment by craigtracey** [comment]
This rebase is definitely not correct. I will take a look shortly.

**Pull request closed without merging**
