### PR TITLE
[#181866559] updated diagrams

### PR DESCRIPTION
**Pull request by YugangW**
Updated diagrams to meet [VMware diagram standards](https://confluence.eng.vmware.com/display/IXCS/Diagrams).

Diagrams prepared by VMware Content Ops Team: https://jira.eng.vmware.com/browse/CO-3460

Signed-off-by: Yugang Wang <wyugang@vmware.com>

### CODE REVIEW

**Comment by craigtracey** [comment]
Thanks for this @YugangW. 

@z4ce will review the images themselves, but we will also need the two failing checks to pass. Please sign the commits.  You may do so with:
```
git commit --amend -s
git push origin diagram-updates -f
```

Additionally please remove the files that these diagrams are replacing. And, again, sign that commit with `git commit -s`

Thanks!

**Comment by YugangW** [comment]
> Thanks for this @YugangW.
> 
> @z4ce will review the images themselves, but we will also need the two failing checks to pass. Please sign the commits. You may do so with:
> 
> ```
> git commit --amend -s
> git push origin diagram-updates -f
> ```
> 
> Additionally please remove the files that these diagrams are replacing. And, again, sign that commit with `git commit -s`
> 
> Thanks!

Hi @craigtracey, As there are 4 commits in this PR I need to sign, I tried to follow the steps [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message#amending-older-or-multiple-commit-messages) to amend all 4 commits and push to remote. Looks like the checks are still failing? Any alternative way you would recommend to bulk sign commits? Thanks!

**Comment by craigtracey** [comment]
Thanks @YugangW.

There are 2 things happening here:
1. You will need to squash your 4 commits into a single commit to add the sign-off. If you are unfamiliar with the process, this might help: https://www.git-tower.com/learn/git/faq/git-squash
2. It looks like you are using the Github "Keep my email address private" [setting](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/blocking-command-line-pushes-that-expose-your-personal-email-address), as your email address is a "noreply" address. Unfortunately, the DCO check requires a "real" email address. 

I am sorry this is onerous - this is the policy of the Open Source Program Office, not those of us who are maintaining this repo. :disappointed:

**Comment by craigtracey** [comment]
closing as this is a duplicate of #192

**Pull request closed without merging**
